spring.application.name=springbootdemo_jdbc_h2

spring.datasource.url=jdbc:postgresql://localhost:5432/demodb
spring.datasource.username=postgres
spring.datasource.password=8695
spring.datasource.driver-class-name=org.postgresql.Driver
